baseURL = 'https://lks2007.github.io/'
languageCode = 'en-us'
title = 'Lukas Soigneux'
theme = "hugo-digital-garden-theme"
themesdir = "themes"
copyright = "Lukas Soigneux ©"

googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  name = "Lukas Soigneux"
  description = "Developper living in France"
  initials = "LS"
  googleAnalytics = ""

  [[params.social]]
    name = "Twitter"
    link = "#"
    icon = "fab fa-twitter"

  [[params.social]]
    name = "Github"
    link = "https://github.com/lks2007"
    icon = "fab fa-github"

  [[params.social]]
    name = "Instagram" 
    link = "https://instagram.com/lukas.sgx_"
    icon = "fab fa-instagram"


[menu]
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 1
  [[menu.main]]
    name = "Features"
    url = "/features/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3


[taxonomies]
  project_tags = 'project_tags'
  feature_tags = 'feature_tags'


[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [markup.highlight]
    # Choose from https://xyproto.github.io/splash/docs/all.html
    style = 'dracula'